version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gh-plate
    main: .
    binary: gh-plate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: gh-plate
    builds:
      - gh-plate
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
